{% set name = "jsonschema-default" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c653ec0e5011fa7514f83442fba5813625c9af80cc535708d53c2eeebadf064b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - xeger >=0.3.5,<0.4.0

test:
  imports:
    - jsonschema_default
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mnboos/jsonschema-default
  summary: Create default objects from a JSON schema
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryanvolz
