{% set name = "jsonschema-default" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonschema-default-{{ version }}.tar.gz
  sha256: 154162d76d3026143d424f249a9c2c08da7f05f1aaea6f3f75756f4fcf959bfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - xeger >=0.3.5,<0.4.0

test:
  imports:
    - jsonschema_default
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mnboos/jsonschema-default
  summary: Create default objects from a JSON schema
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryanvolz
