{% set name = "jsonschema-default" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c653ec0e5011fa7514f83442fba5813625c9af80cc535708d53c2eeebadf064b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    # max version on poetry until pyproject.toml tool.poetry.homepage is a valid URI
    - poetry <1.6
  run:
    - loguru >=0.7.0
    - python >={{ python_min }}
    - rstr >=3.2.1

test:
  imports:
    - jsonschema_default
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mnboos/jsonschema-default
  summary: Create default objects from a JSON schema
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryanvolz
