{% set name = "jsonschema-default" %}
{% set version = "1.8.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 77e35e4a95519c7dbdbe25438c00af33c17bb766cbb0a29a2aa9d645ee3c1399

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - rstr ==3.2.2

test:
  imports:
    - jsonschema_default
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mnboos/jsonschema-default
  summary: Create default objects from a JSON schema
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryanvolz
